version: '3'
services:
  jupyter:
    container_name: jupyter
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8001:8888
    command: jupyter lab --port 8888 --ip=0.0.0.0 --allow-root

